<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="Skybitz_Maintanance_MainScripts.Warehouse" tests="1" time="268.142" ignored="0" failures="0" timestamp="07 Feb 2018 06:40:28 GMT" skipped="0" hostname="svcs-PC" errors="1">
  <testcase name="Main_Functionalitites" time="268.142" classname="Skybitz_Maintanance_MainScripts.Warehouse">
    <error type="java.io.FileNotFoundException" message="C:\Users\svcs\Dropbox\QA\TestData (Single Iteration and Bulk Upload)\SmartLynx_QA_NewAutomationFramework_TestData.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\svcs\Dropbox\QA\TestData (Single Iteration and Bulk Upload)\SmartLynx_QA_NewAutomationFramework_TestData.xlsx (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at Utility.ExcelUtils.setCellData(ExcelUtils.java:136)
	at Warehouse_Subclasses.Warehouse_Methods.alreadyexistfile(Warehouse_Methods.java:421)
	at Warehouse_Subclasses.AlreadyExistWarehouse_Functionality.Warehouse(AlreadyExistWarehouse_Functionality.java:61)
	at Skybitz_Maintanance_MainScripts.Warehouse.Main_Functionalitites(Warehouse.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- Main_Functionalitites -->
</testsuite> <!-- Skybitz_Maintanance_MainScripts.Warehouse -->
